global:
  resolve_timeout: 5m
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@self-healing-app.com'

templates:
  - '/etc/alertmanager/templates/*.tmpl'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'self-healing-webhook'
  routes:
    # 1. لو الإنذار auto-remediate أو critical، شغل الـ Webhook أولاً وكمل
    - match:
        severity: auto-remediate
      receiver: 'self-healing-webhook'
      continue: true

    - match:
        severity: critical
      receiver: 'self-healing-webhook'
      continue: true

    # 2. بعد الـ Webhook، ابعت التنبيه لسلاك الخاص بالـ critical
    - match:
        severity: critical
      receiver: 'slack-critical'
      continue: true

    # 3. لو الإنذار warning ابعته لقناة الـ warnings
    - match:
        severity: warning
      receiver: 'slack-warnings'

receivers:
  - name: 'default'
    slack_configs:
      - api_url: 'http://13.222.99.21:8080/dummy-slack'
        channel: '#alerts'
        title: 'Self-Healing Alert'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}'

  - name: 'self-healing-webhook'
    webhook_configs:
      - url: 'http://10.0.101.161:5000/webhook'
        send_resolved: false

  - name: 'slack-critical'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/T0BG7HTGE67/B0BGAGR4T5K/ZMLBVjmjvZhgNvtfHlJr1A'
        channel: '#all-critical-alerts'
        title: 'CRITICAL: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Instance:* {{ .Labels.instance }}
          *Severity:* {{ .Labels.severity }}
          *Time:* {{ .StartsAt }}
          {{ end }}
        send_resolved: true

  - name: 'slack-warnings'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/T0BG7HTGE67/B0BGFPJQYM7/oYgOTxVlRX98hnTXwUMReC'
        channel: '#warnning'
        title: 'WARNING: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Instance:* {{ .Labels.instance }}
          {{ end }}
        send_resolved: true
