global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'self-healing-monitor'

rule_files:
  - 'alert_rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # التعديل الجديد عشان بروميثيوس يراقب التطبيق المحلي بتاعنا
  - job_name: 'nodejs_app'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['172.17.0.1:3000']
